- name: "cheese"
  description: "Take photos and videos with your webcam, with fun graphical effects"
  critical: false
  hidden: false
  selected: false
  packages:
    - cheese
- name: "font-manager-git"
  description: "Manage your fonts with ease."
  critical: false
  hidden: false
  selected: false
  packages:
    - font-manager-git
- name: "galculator"
  description: "GTK+ based scientific calculator"
  critical: false
  hidden: false
  selected: false
  packages:
    - galculator
- name: "flameshot"
  description: "Powerful yet simple to use screenshot software"
  critical: false
  hidden: false
  selected: false
  packages:
    - flameshot
- name: "liferea"
  description: "A desktop news aggregator for online news feeds and weblogs"
  critical: false
  hidden: false
  selected: false
  packages:
      - liferea
- name: "mediainfo"
  description: "	Supplies technical and tag information about a video or audio file (CLI interface)"
  critical: false
  hidden: false
  selected: false
  packages:
      - mediainfo
- name: "mcomix"
  description: "	A user-friendly, customizable image viewer specifically designed to handle comic books"
  critical: false
  hidden: false
  selected: false
  packages:
      - mcomix
- name: "pdfarranger"
  description: "Helps merge or split PDF documents and rotate, crop and rearrange pages"
  critical: false
  hidden: false
  selected: false
  packages:      
    - pdfarranger
- name: "plank"
  description: "Elegant, simple, clean dock"
  critical: false
  hidden: false
  selected: false
  packages:      
    - plank
- name: "Plank Themes"
  description: "from Arco Linux"
  critical: false
  hidden: false
  selected: false
  packages:      
    - arcolinux-plank-themes-git
- name: "screenkey"
  description: "A screencast tool to display your keys inspired by Screenflick"
  critical: false
  hidden: false
  selected: false
  packages:
    - screenkey-git
- name: "xfburn"
  description: "A simple CD/DVD burning tool based on libburnia libraries"
  critical: false
  hidden: false
  selected: false
  packages:
    - xfburn
- name: "File Manager"
  description: "Filemanager"
  critical: false
  hidden: false
  selected: false
  packages:
    - caja
    - dolphin
    - mc
    - nautilus
    - nemo
    - nemo-fileroller
    - pcmanfm
    - ranger
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - terminus-font
- name: "Git"
  description: "Git"
  critical: false
  hidden: false
  selected: false
  packages:
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - gimp
    - gimp-plugin-gmic
    - gpick
    - inkscape
    - krita
    - nitrogen
    - nomacs
    - pinta
- name: "Fun"
  description: "Fun"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Password Manager"
  description: "Password manager"
  critical: false
  hidden: false
  selected: false
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Terminals"
  description: "Terminals"
  critical: false
  hidden: false
  selected: false
  packages:
    - alacritty
    - gnome-terminal
    - guake
    - kitty
    - konsole
    - lxterminal
    - sakura
    - terminator
    - termite
    - tilix
    - tilda
    - tmux
- name: "Usb"
  description: "Usb"
  critical: false
  hidden: false
  selected: false
  packages:
    - etcher-bin
    - imagewriter
    - mintstick-git
    - woeusb
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "Zsh"
  description: "Zsh"
  critical: false
  hidden: false
  selected: false
  packages:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - oh-my-zsh-git
    - arcolinux-zsh-git
